services:
  orthanc:
    container_name: orthanc
    image: orthancteam/orthanc
    volumes:
      - ./orthanc-config/plugins.json:/etc/orthanc/plugins.json
      # see StorageDirectory in orthanc-config/plugins.json
      - ./storage/orthanc/storage/:/var/lib/orthanc/storage/
      # see IndexDirectory in orthanc-config/plugins.json
      - ./storage/orthanc/index/:/var/lib/orthanc/index/
      # see TemporaryDirectory in orthanc-config/plugins.json
      - ./storage/orthanc/tmp/:/tmp/Orthanc/
    ports:
      - 8042:8042
      - 4242:4242
    environment:
      VERBOSE_ENABLED: "true"
    networks:
      - "orthanc-network"
    depends_on:
      - mysql-server
    #   - authorization-server

  postgres-server:
    container_name: postgres
    image: postgres:14
    restart: unless-stopped
    volumes:
      - "./storage/database:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: orthanc
      POSTGRES_USER: orthanc
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    networks:
      - "orthanc-network"
networks:
  orthanc-network:
    name: orthanc-network
    driver: bridge
